/// Represents a Surah of the Holy Quran.
class Surah {
  final int number;
  final String nameAr;
  final String nameEn;
  final int versesCount;
  final String type; // مكية or مدنية

  const Surah({
    required this.number,
    required this.nameAr,
    required this.nameEn,
    required this.versesCount,
    required this.type,
  });

  /// Formatted Surah number with leading zeros (e.g. 001, 012, 114)
  String get formattedNumber => number.toString().padLeft(3, '0');

  /// Complete list of the 114 Surahs of the Holy Quran.
  static const List<Surah> allSurahs = [
    Surah(number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatihah', versesCount: 7, type: 'مكية'),
    Surah(number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', versesCount: 286, type: 'مدنية'),
    Surah(number: 3, nameAr: 'آل عمران', nameEn: 'Ali \'Imran', versesCount: 200, type: 'مدنية'),
    Surah(number: 4, nameAr: 'النساء', nameEn: 'An-Nisa\'', versesCount: 176, type: 'مدنية'),
    Surah(number: 5, nameAr: 'المائدة', nameEn: 'Al-Ma\'idah', versesCount: 120, type: 'مدنية'),
    Surah(number: 6, nameAr: 'الأنعام', nameEn: 'Al-An\'am', versesCount: 165, type: 'مكية'),
    Surah(number: 7, nameAr: 'الأعراف', nameEn: 'Al-A\'raf', versesCount: 206, type: 'مكية'),
    Surah(number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', versesCount: 75, type: 'مدنية'),
    Surah(number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', versesCount: 129, type: 'مدنية'),
    Surah(number: 10, nameAr: 'يونس', nameEn: 'Yunus', versesCount: 109, type: 'مكية'),
    Surah(number: 11, nameAr: 'هود', nameEn: 'Hud', versesCount: 123, type: 'مكية'),
    Surah(number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', versesCount: 111, type: 'مكية'),
    Surah(number: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra\'d', versesCount: 43, type: 'مدنية'),
    Surah(number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', versesCount: 52, type: 'مكية'),
    Surah(number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', versesCount: 99, type: 'مكية'),
    Surah(number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', versesCount: 128, type: 'مكية'),
    Surah(number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra\'', versesCount: 111, type: 'مكية'),
    Surah(number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', versesCount: 110, type: 'مكية'),
    Surah(number: 19, nameAr: 'مريم', nameEn: 'Maryam', versesCount: 98, type: 'مكية'),
    Surah(number: 20, nameAr: 'طه', nameEn: 'Taha', versesCount: 135, type: 'مكية'),
    Surah(number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya\'', versesCount: 112, type: 'مكية'),
    Surah(number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', versesCount: 78, type: 'مدنية'),
    Surah(number: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu\'minun', versesCount: 118, type: 'مكية'),
    Surah(number: 24, nameAr: 'النور', nameEn: 'An-Nur', versesCount: 64, type: 'مدنية'),
    Surah(number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', versesCount: 77, type: 'مكية'),
    Surah(number: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu\'ara\'', versesCount: 227, type: 'مكية'),
    Surah(number: 27, nameAr: 'النمل', nameEn: 'An-Naml', versesCount: 93, type: 'مكية'),
    Surah(number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', versesCount: 88, type: 'مكية'),
    Surah(number: 29, nameAr: 'العنكبوت', nameEn: 'Al-\'Ankabut', versesCount: 69, type: 'مكية'),
    Surah(number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', versesCount: 60, type: 'مكية'),
    Surah(number: 31, nameAr: 'لقمان', nameEn: 'Luqman', versesCount: 34, type: 'مكية'),
    Surah(number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', versesCount: 30, type: 'مكية'),
    Surah(number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', versesCount: 73, type: 'مدنية'),
    Surah(number: 34, nameAr: 'سبأ', nameEn: 'Saba\'', versesCount: 54, type: 'مكية'),
    Surah(number: 35, nameAr: 'فاطر', nameEn: 'Fatir', versesCount: 45, type: 'مكية'),
    Surah(number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', versesCount: 83, type: 'مكية'),
    Surah(number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', versesCount: 182, type: 'مكية'),
    Surah(number: 38, nameAr: 'ص', nameEn: 'Sad', versesCount: 88, type: 'مكية'),
    Surah(number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', versesCount: 75, type: 'مكية'),
    Surah(number: 40, nameAr: 'غافر', nameEn: 'Ghafir', versesCount: 85, type: 'مكية'),
    Surah(number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', versesCount: 54, type: 'مكية'),
    Surah(number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', versesCount: 53, type: 'مكية'),
    Surah(number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', versesCount: 89, type: 'مكية'),
    Surah(number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', versesCount: 59, type: 'مكية'),
    Surah(number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', versesCount: 37, type: 'مكية'),
    Surah(number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', versesCount: 35, type: 'مكية'),
    Surah(number: 47, nameAr: 'محمد', nameEn: 'Muhammad', versesCount: 38, type: 'مدنية'),
    Surah(number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', versesCount: 29, type: 'مدنية'),
    Surah(number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', versesCount: 18, type: 'مدنية'),
    Surah(number: 50, nameAr: 'ق', nameEn: 'Qaf', versesCount: 45, type: 'مكية'),
    Surah(number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', versesCount: 60, type: 'مكية'),
    Surah(number: 52, nameAr: 'الطور', nameEn: 'At-Tur', versesCount: 49, type: 'مكية'),
    Surah(number: 53, nameAr: 'النجم', nameEn: 'An-Najm', versesCount: 62, type: 'مكية'),
    Surah(number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', versesCount: 55, type: 'مكية'),
    Surah(number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', versesCount: 78, type: 'مدنية'),
    Surah(number: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi\'ah', versesCount: 96, type: 'مكية'),
    Surah(number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', versesCount: 29, type: 'مدنية'),
    Surah(number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadila', versesCount: 22, type: 'مدنية'),
    Surah(number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', versesCount: 24, type: 'مدنية'),
    Surah(number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', versesCount: 13, type: 'مدنية'),
    Surah(number: 61, nameAr: 'الصف', nameEn: 'As-Saff', versesCount: 14, type: 'مدنية'),
    Surah(number: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu\'ah', versesCount: 11, type: 'مدنية'),
    Surah(number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', versesCount: 11, type: 'مدنية'),
    Surah(number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', versesCount: 18, type: 'مدنية'),
    Surah(number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', versesCount: 12, type: 'مدنية'),
    Surah(number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', versesCount: 12, type: 'مدنية'),
    Surah(number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', versesCount: 30, type: 'مكية'),
    Surah(number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', versesCount: 52, type: 'مكية'),
    Surah(number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', versesCount: 52, type: 'مكية'),
    Surah(number: 70, nameAr: 'المعارج', nameEn: 'Al-Ma\'arij', versesCount: 44, type: 'مكية'),
    Surah(number: 71, nameAr: 'نوح', nameEn: 'Nuh', versesCount: 28, type: 'مكية'),
    Surah(number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', versesCount: 28, type: 'مكية'),
    Surah(number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', versesCount: 20, type: 'مكية'),
    Surah(number: 74, nameAr: 'المدثر', nameEn: 'Al-Dathir', versesCount: 56, type: 'مكية'),
    Surah(number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', versesCount: 40, type: 'مكية'),
    Surah(number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', versesCount: 31, type: 'مدنية'),
    Surah(number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', versesCount: 50, type: 'مكية'),
    Surah(number: 78, nameAr: 'النبأ', nameEn: 'An-Naba\'', versesCount: 40, type: 'مكية'),
    Surah(number: 79, nameAr: 'النازعات', nameEn: 'An-Nazi\'at', versesCount: 46, type: 'مكية'),
    Surah(number: 80, nameAr: 'عبس', nameEn: 'Abasa', versesCount: 42, type: 'مكية'),
    Surah(number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', versesCount: 29, type: 'مكية'),
    Surah(number: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', versesCount: 19, type: 'مكية'),
    Surah(number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', versesCount: 36, type: 'مكية'),
    Surah(number: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', versesCount: 25, type: 'مكية'),
    Surah(number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', versesCount: 22, type: 'مكية'),
    Surah(number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', versesCount: 17, type: 'مكية'),
    Surah(number: 87, nameAr: 'الأعلى', nameEn: 'Al-A\'la', versesCount: 19, type: 'مكية'),
    Surah(number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', versesCount: 26, type: 'مكية'),
    Surah(number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', versesCount: 30, type: 'مكية'),
    Surah(number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', versesCount: 20, type: 'مكية'),
    Surah(number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', versesCount: 15, type: 'مكية'),
    Surah(number: 92, nameAr: 'الليل', nameEn: 'Al-Layl', versesCount: 21, type: 'مكية'),
    Surah(number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', versesCount: 11, type: 'مكية'),
    Surah(number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', versesCount: 8, type: 'مكية'),
    Surah(number: 95, nameAr: 'التين', nameEn: 'At-Tin', versesCount: 8, type: 'مكية'),
    Surah(number: 96, nameAr: 'العلق', nameEn: 'Al-\'Alaq', versesCount: 19, type: 'مكية'),
    Surah(number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', versesCount: 5, type: 'مكية'),
    Surah(number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', versesCount: 8, type: 'مدنية'),
    Surah(number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', versesCount: 8, type: 'مدنية'),
    Surah(number: 100, nameAr: 'العاديات', nameEn: 'Al-\'Adiyat', versesCount: 11, type: 'مكية'),
    Surah(number: 101, nameAr: 'القارعة', nameEn: 'Al-Qari\'ah', versesCount: 11, type: 'مكية'),
    Surah(number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', versesCount: 8, type: 'مكية'),
    Surah(number: 103, nameAr: 'العصر', nameEn: 'Al-\'Asr', versesCount: 3, type: 'مكية'),
    Surah(number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', versesCount: 9, type: 'مكية'),
    Surah(number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', versesCount: 5, type: 'مكية'),
    Surah(number: 106, nameAr: 'قريش', nameEn: 'Quraysh', versesCount: 4, type: 'مكية'),
    Surah(number: 107, nameAr: 'الماعون', nameEn: 'Al-Ma\'un', versesCount: 7, type: 'مكية'),
    Surah(number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', versesCount: 3, type: 'مكية'),
    Surah(number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', versesCount: 6, type: 'مكية'),
    Surah(number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', versesCount: 3, type: 'مدنية'),
    Surah(number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', versesCount: 5, type: 'مكية'),
    Surah(number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', versesCount: 4, type: 'مكية'),
    Surah(number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', versesCount: 5, type: 'مكية'),
    Surah(number: 114, nameAr: 'الناس', nameEn: 'An-Nas', versesCount: 6, type: 'مكية'),
  ];

  /// Find Surah by number
  static Surah findByNumber(int number) {
    return allSurahs.firstWhere(
      (s) => s.number == number,
      orElse: () => allSurahs.first,
    );
  }

  /// Get the start page in standard Madinah Mushaf (1-604)
  int get startPage => _surahStartPages[number] ?? 1;

  static const Map<int, int> _surahStartPages = {
    1: 1, 2: 2, 3: 50, 4: 77, 5: 106, 6: 128, 7: 151, 8: 177, 9: 187, 10: 208,
    11: 221, 12: 235, 13: 249, 14: 255, 15: 262, 16: 267, 17: 282, 18: 293, 19: 305, 20: 312,
    21: 322, 22: 332, 23: 342, 24: 350, 25: 359, 26: 367, 27: 377, 28: 385, 29: 396, 30: 404,
    31: 411, 32: 415, 33: 418, 34: 428, 35: 434, 36: 440, 37: 446, 38: 453, 39: 458, 40: 467,
    41: 477, 42: 483, 43: 489, 44: 496, 45: 499, 46: 502, 47: 507, 48: 511, 49: 515, 50: 518,
    51: 520, 52: 523, 53: 526, 54: 528, 55: 531, 56: 534, 57: 537, 58: 542, 59: 545, 60: 549,
    61: 551, 62: 553, 63: 554, 64: 556, 65: 558, 66: 560, 67: 562, 68: 564, 69: 566, 70: 568,
    71: 570, 72: 572, 73: 574, 74: 575, 75: 577, 76: 578, 77: 580, 78: 582, 79: 583, 80: 585,
    81: 586, 82: 587, 83: 587, 84: 589, 85: 590, 86: 591, 87: 591, 88: 592, 89: 593, 90: 594,
    91: 595, 92: 596, 93: 596, 94: 597, 95: 597, 96: 597, 97: 598, 98: 598, 99: 599, 100: 599,
    101: 600, 102: 600, 103: 601, 104: 601, 105: 601, 106: 602, 107: 602, 108: 602, 109: 603, 110: 603,
    111: 603, 112: 604, 113: 604, 114: 604
  };
}
